### ISSUE TITLE
SharePoint  -ObjecIDs

### ISSUE THREAD

**Issue by Pri9999** [invictus-ir/Microsoft-Extractor-Suite#87]
Hey there
Thank you for creating this script to get UALs, has been very helpful. 
I was trying to get UAL for a particular SharePoint site using **-ObjecIDs** parameter.
Reviewing the UAL documentation, I was unable to find references to using -ObjecIDs while collecting SharePoint UALs.
Is this something that is supported at the moment or is it in the pipeline for future releases. 
Thanks
Pri

**Comment by Calvindd2f** [comment]
It's definitely a parameter for the auditData body, defined as : 


|  objectId              | String                      |  For Exchange admin audit logging, the name of the object modified by the cmdlet. For SharePoint activity, the full URL path name of the file or folder accessed by a user. For Microsoft Entra activity, the name of the user account that was modified.|
|--------------------|----------------------|-----------|

In the file itself it is not a defined parameter, likely from lack of interest in needing it. 

```powershell
<#
.PARAMETER ObjecIDs 
     Exact data returned depends on the service in the current `@odatatype.microsoft.graph.security.auditLogQuery` record.
     For Exchange admin audit logging, the name of the object modified by the cmdlet.
     For SharePoint activity, the full URL path name of the file or folder accessed by a user. 
     For Microsoft Entra activity, the name of the user account that was modified.|
#>
```

The ObjectID is defined in the body that is converted to JSON, but not as a defined parameter as per previously stated.

```powershell
$body = @{
        "@odata.type" = "#microsoft.graph.security.auditLogQuery"
        displayName = $searchName
        filterStartDateTime = $script:startDate
        filterEndDateTime = $script:endDate
        recordTypeFilters = $RecordType
        keywordFilter = $Keyword
        serviceFilter = $Service
        operationFilters = $Operations
        userPrincipalNameFilters = $UserIds
        ipAddressFilters = $IPAddress
        objectIdFilters = $ObjecIDs                             # Here <---
        administrativeUnitIdFilters = @()
        status = ""
    } | ConvertTo-Json
````

Implementing it would only really require a named parameter like below:

```powershell
[CmdletBinding()]
    param(
		[Parameter(Mandatory=$true)]$searchName,
        [string]$OutputDir = "Output\UnifiedAuditLog\",
        [string]$Encoding = "UTF8",
        [string]$startDate,
        [string]$endDate,
        [string[]]$RecordType = @(),
        [string]$Keyword = "",
        [string]$Service = "",
        [string[]]$Operations = @(),
        [string[]]$UserIds = @(),
        [string[]]$IPAddress = @(),
        [string[]]$ObjecIDs = @()                             # Here <---
    )
````'

To actually answer your question it is not available at the moment, I can't say whether it will be included or not but with the above information , you should be able to modify the source file if you are in a bind. I cannot see there being any reason to not include it in future though

**Comment by JoeyInvictus** [comment]
Hi, I added the requested Object IDs as requested. Can you test if it works? I pushed the changes to this repository, not to the PowerShell Gallery/Releases page (yet). You can download the repository, import the module, and try again.

Thanks, @Calvindd2f , for making my life easier :)

**Comment by Pri9999** [comment]
> Hi, I added the requested Object IDs as requested. Can you test if it works? I pushed the changes to this repository, not to the PowerShell Gallery/Releases page (yet). You can download the repository, import the module, and try again.
> 
> Thanks, @Calvindd2f , for making my life easier :)

Hi @Calvindd2f
Thanks so much for your quick response. I'm still unable to extract logs for this parameter. 
![Capture](https://github.com/user-attachments/assets/1445e739-06bc-4539-a33b-4a2d89d0eecd)

I have attached a screenshot of the query I ran and the error. Also, the **-ObjectIDs** had link to my OneDrive location. 

Thanks

**Comment by JoeyInvictus** [comment]
Hi, sorry about that! For some reason, I assumed you were using the `Get-UALGraph` function. The tool supports both the `Search-UnifiedAuditLog` cmdlet and acquisition via `Graph`. I've now added it to the `Get-UALAll` function you're running. 

Can you let me know if it works? I'll need to do some additional testing before pushing it to the Gallery and Release pages, just to make sure it didn't break anything.

**Comment by JoeyInvictus** [comment]
Hi, did you manage to test this?
