### ISSUE TITLE
Email Download Issue

### ISSUE THREAD

**Issue by shudon** [invictus-ir/Microsoft-Extractor-Suite#91]
I just got this suite installed, and it's working fantastic. However for some reason when I run the below command it pulls about 50 emails then eventually errors out. I ran this without the download and it returns all the expected messageIDs. I also tried running this through the get-email commands and get the same error. I've confirmed the app has the following permissions: 

Mail.ReadBasic.All
Mail.ReadWrite
Mail.Send
User.Read
User.Read.All

This is the command I'm using: 
Get-messageids -StartDate 9/19/2024 -EndDate 9/20/2024 -IP <removed> -Download $true

This is the error I see: 
[INFO] Ensure you are connected to Microsoft Graph by running the Connect-MgGraph -Scopes Mail.ReadBasic.All command before executing this script
[WARNING] The 'Mail.ReadBasic.All' is an application-level permission, requiring an application-based connection through the 'Connect-MgGraph' command for its use.
[WARNING] Error Message: Cannot find an overload for "ToString" and the argument count: "1". -Color Red
Cannot find an overload for "ToString" and the argument count: "1".
At C:\Program Files\WindowsPowerShell\Modules\Microsoft-Extractor-Suite\2.0.2\Scripts\Get-MailItemsAccessed.ps1:671 char:9
+         $ReceivedDateTime = $getMessage.ReceivedDateTime.ToString("yy ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

**Comment by JoeyInvictus** [comment]
Hi, interesting issue. I fixed part of the error — the `-Color Red` was a small mistake on my side, but this shouldn’t be causing the issue. However, it seems the error is happening on this line (671):

`$ReceivedDateTime = $getMessage.ReceivedDateTime.ToString("yyyyMMdd_HHmmss")`

It might be trying to format a null value or something similar. I can try generating some messages in our test environment and reproducing the error next week, but I’ll need some time.

If you'd like to do some troubleshooting yourself, you can try adding the following between line 670 and 671 in `/scripts/Get-MailItemsAccessed.ps1`:

`Write-Host "ReceivedDateTime: $($getMessage.ReceivedDateTime)"`

This will print the raw value that the script is trying to format to a string. It might help us understand why it's causing an error.

In addition, we can add an if/else statement to proceed if the string is empty. This will ensure that all emails are downloaded, and it will skip the ones causing the error. It's not a perfect solution, but it might keep you going for now. Replace line 671 with the following:


```
if ($getMessage.ReceivedDateTime) {
    $ReceivedDateTime = $getMessage.ReceivedDateTime.ToString("yyyyMMdd_HHmmss")
    Write-Host "Formatted ReceivedDateTime: $ReceivedDateTime"
} else {
    Write-Host "ReceivedDateTime is null, using current date/time as fallback."
    $ReceivedDateTime = (Get-Date).ToString("yyyyMMdd_HHmmss")
}
```

**Comment by JoeyInvictus** [comment]
Hi, I pushed some new code to GitHub. Let me know if it fixes your issue.

**Comment by shudon** [comment]
I just tried again after the update. Different error now: 

You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft-Extractor-Suite\2.0.3\Scripts\Get-MailItemsAccessed.ps1:668 char:9
+         $ReceivedDateTime = $getMessage.ReceivedDateTime.ToString("yy ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by JoeyInvictus** [comment]
Hmm, I pushed some new code to GitHub. Can you give it another try? 

I added an extra try/catch to work around this issue by adding the prefix unabletogetdate-{subject}.eml instead of throwing an error. I am unable to reproduce the error; I’ve been downloading batches of 100 to 200 emails without issue. It feels strange that it can find the email but not retrieve the date from it.

**Comment by shudon** [comment]
Sorry just tried again, still getting that error. Could that permission warning be the issue? Not sure why it always says that when it's clearly downloading emails before it gets to this. 

[WARNING] The 'Mail.ReadBasic.All' is an application-level permission, requiring an application-based connection through the 'Connect-MgGraph' command for its use.
[WARNING] Error Message: You cannot call a method on a null-valued expression.
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\Microsoft-Extractor-Suite\2.0.3\Scripts\Get-MailItemsAccessed.ps1:668 char:9
+         $ReceivedDateTime = $getMessage.ReceivedDateTime.ToString("yy ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by JoeyInvictus** [comment]
Hmm, strange. The error is wrapped in a try/catch block, and it will print the real error message along with a warning. It was quite common for people not to use the `Mail.ReadBasic.All` permission, so I added it as a warning. However, it should be `Mail.ReadWrite`, so I will update the warning accordingly.

```
Write-logFile -Message "[WARNING] The 'Mail.ReadBasic.All' permission is an application-level permission, requiring an application-based connection through the 'Connect-MgGraph' command for its use." -Color "Red"
Write-Host "[WARNING] Error Message: $($_.Exception.Message)"
```

Could you try bypassing the Extractor and running the command manually? This will help us see what output it generates. Replace `$MessageID` with the actual message ID, and `$userId` with the username associated with the email.

`Get-MgUserMessage -Filter "internetMessageId eq '$MessageID'" -UserId $userId `

P.S. Did you pull the latest code from the GitHub repository? You're still encountering an error on line 668, but that line is empty in the current version of the code. Might have to do a `remove-module` first and then `import-module` again.

![image](https://github.com/user-attachments/assets/f6e3f7dd-addc-4e8c-8b7d-38fd67bf861f)

**Comment by shudon** [comment]
I was using update-module and the error has the version 2.0.3 in the error, is that correct? I just tried remove-module and install-module and still the same error on the same line. 

I ran the get-mgusermessage and those ran fine.

**Comment by JoeyInvictus** [comment]
Ah, sorry for the confusion. I’ve only pushed the code to the GitHub repository, not yet to the PowerShell Gallery or the release pages. We try to avoid creating new versions for every small change while troubleshooting. We only push to the Gallery and Release pages once everything is working properly. Unfortunately there is no way to modify a version after pushing it to the Gallery.

To test the latest changes, the approach would be:

1. Download the repository from: https://github.com/invictus-ir/Microsoft-Extractor-Suite

2. Ensure that the old module is removed using:
`Remove-Module Microsoft-Extractor-Suite`

3. Import the updated module:
`Import-Module .\Microsoft-Extractor-Suite.psd1`

Then run the commando you want to run again.

**Comment by shudon** [comment]
Oh my mistake, this is the first github repo I've used. I downloaded your updated and tried it again. Here is the error: 

[WARNING] ReceivedDateTime is not a valid DateTime object, using 'unabletogetdate'
[INFO] Ensure you are connected to Microsoft Graph by running the Connect-MgGraph -Scopes Mail.ReadBasic.All command before executing this script
[WARNING] The 'Mail.ReadBasic.All' is an application-level permission, requiring an application-based connection through the 'Connect-MgGraph' command for its use.
[WARNING] Error Message: Cannot bind argument to parameter 'MessageId' because it is an empty string.
Get-MgUserMessageContent : Cannot bind argument to parameter 'MessageId' because it is an empty string.
At C:\Scripts\Extractor\Microsoft-Extractor-Suite-main\Microsoft-Extractor-Suite-main\Scripts\Get-MailItemsAccessed.ps1:680 char:45
+         Get-MgUserMessageContent -MessageId $messageId -UserId $userI ...
+                                             ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-MgUserMessageContent], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Get-MgUserMessageContent

**Comment by shudon** [comment]
I tried added your snippet from the start of this thread that would use the current date/time if it was missing, which I can see it was null. Still got this error: 

ReceivedDateTime is null, using current date/time as fallback.
[WARNING] The 'Mail.ReadBasic.All' is an application-level permission, requiring an application-based connection through the 'Connect-MgGraph' command for its use.
[WARNING] Error Message: Cannot bind argument to parameter 'MessageId' because it is an empty string.
Get-MgUserMessageContent : Cannot bind argument to parameter 'MessageId' because it is an empty string.
At C:\Scripts\Extractor\Microsoft-Extractor-Suite-main\Microsoft-Extractor-Suite-main\Scripts\Get-MailItemsAccessed.ps1:688 char:45

**Comment by shudon** [comment]
So I was able to get it to at least run through all the message IDs by putting the whole get-mailmessaeg section into a try/catch. I also added a line to print the messageid value when it fails. For some reason some of the messages it gets have no value for the message id or the receive date. Any idea what could cause that? All in total there were 3 emails out of 111 that had that issue. 

ReceivedDateTime is null, using current date/time as fallback.
Message ID =
ReceivedDateTime is null, using current date/time as fallback.
Message ID =

**Comment by JoeyInvictus** [comment]
I'm not entirely sure what the issue could be either. I tried to reproduce it in our test environment, but I wasn’t able to get a result without a message ID. Could you check the three messages to see if they belong to a shared mailbox, or perhaps the message no longer exists in the mailbox?

Here's the process: `Get-MessageIDs` retrieves the message ID from the log event, and then we use `Get-MgUserMessage -Filter "internetMessageId eq '$onlyMessageID'" -UserId $userId` to get information about the email. Maybe the message was either deleted or can't be found due to a mismatch between the ID and the user.

If you have the message ID, you could try running a Content Search using that ID to check if the message is still available in the user's mailbox. This can help confirm whether the message was deleted or if it's just not appearing due to a mismatch in the combination of the ID and the user.

**Comment by JoeyInvictus** [comment]
Okay, I think the issue is related to the message being deleted. I removed the email from the mailbox and received the same error you encountered. I’ll add a try/catch block to handle this, indicating that the email might no longer be available.

**Comment by JoeyInvictus** [comment]
This seems to do the job:

```
try {
            Get-MgUserMessageContent -MessageId $messageId -UserId $userId -OutFile $filePath
            Write-logFile -Message "[INFO] Output written to $filePath" -Color "Green"
        } catch {
            if ($_.Exception.Message -like "*Cannot bind argument to parameter 'MessageId' because it is an empty string*") {
                Write-logFile -Message "[WARNING] Message with ID '$iMessageID' was likely deleted or the ID is missing." -Color "Red"
            } else {
                throw 
            }
        }
```

![image](https://github.com/user-attachments/assets/3b38bf05-223b-4aae-9de0-99403caf5593)

**Comment by shudon** [comment]
Thanks, I put that in place and it's working as expected. 

I guess I wouldn't expect deleting the email from the user mailbox to actually remove it like that. There is a retention policy and even if it was deleted it should go into recoverable for 30 days which is within my search range. I wonder if this happens when MS does the Zap action on a malicious email.

**Comment by JoeyInvictus** [comment]
I didn't do extensive testing, but it seems that if you remove the message and it moves to recoverable items, you can still download it. I suppose this is because it’s just another folder within the user's mailbox. However, if you delete it from the recoverable items, you can't download it anymore with the script.

**Comment by JoeyInvictus** [comment]
The fix is pushed to the the new version, feel free to re-open the issue if you have any other suggestions/feedback.

**Comment by shudon** [comment]
I appreciate all the help, thanks!
